export { default as CartPage } from './Cart'
export { default as CheckoutPage } from './Checkout'
export { default as FavouritePage } from './Favourite'
export { default as ProductsPage } from './Products'
export { default as SearchPage } from './Search'
export { default as ProfilePage } from './Profile'
export { default as LoginPage } from './Login'
export { default as SignUpPage } from './SignUp'
